name:       'DUB'
baseurl:    ''

brandimage: 'images/nav-logo.png'
brandtext:  'DUB'

lessc: node_modules/.bin/lessc

navbar:
  items:
    - text: 'Home'
      link: 'index.html'
    - text: 'About DUB'
      link: 'aboutdub.html'
    - text: 'Calendar'
      link: 'calendar.html'
#    - text: 'People'
#      link: 'people.html'
#    - text: 'Resources'
#      link: 'resources.html'
    - text: 'Getting Involved'
      link: 'gettinginvolved.html'

collections:
  people:
    output: true

defaults:
  - scope:
      type: people
    values:
      layout: person

exclude:
  # Bootstrap
  - bootstrap/less
  # Node
  - node_modules
  - npm-shrinkwrap.json
  - package.json
  # Python
  - env34
  - env35
  - requirements3.txt
  - tasks.py
  - tasks.pyc
  # README
  - README.md
  # Ruby
  - Gemfile
  - Gemfile.lock
  # Tests
  - tests
