name:       DUB
baseurl:    ''

collections:
  people:
    output: true

exclude:
  # Our Python
  - env34
  - requirements3.txt
  - tasks.py
  - tasks.pyc
  # Project README
  - README.md
  # Tests
  - tests
