name:       DUB
baseurl:    ''

collections:
  people:
    output: true

defaults:
  - scope:
      type: people
    values:
      layout: person

exclude:
  # Our Python
  - env34
  - requirements3.txt
  - tasks.py
  - tasks.pyc
  # Project README
  - README.md
  # Tests
  - tests
